# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    # role_hierarchy:
    #     ROLE_ADMIN:       ROLE_BLOGGER
    #     ROLE_BLOGGER:     ROLE_USER
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: martin
                        roles: 'ROLE_BLOGGER'
                    admin:
                        password: 1234
                        roles: [ ROLE_ADMIN, ROLE_BLOGGER ]

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /login

    access_control:
        # require ROLE_ADMIN for /admin*}
        - { path: ^/post/new, roles: [ ROLE_ADMIN, ROLE_BLOGGER ] }
        - { path: /delete$, roles: [ ROLE_ADMIN ] }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
